census <- read.csv("./data/census.csv")
set.seed(2000)
library(caTools)
split = sample.split(census$over50k,SplitRatio = 0.6)
train = subset(census,split == TRUE)
test = subset(census,split == FALSE)
logistcModel = glm(over50k ~ ., data = train, family = binomial)
summary(logistcModel)
predictTest = predict(logistcModel,type = "response", newdata = test )
table(test$over50k,predictTest > 0.5)
(9051+1888)/nrow(test)
table(test$over50k)
9713/nrow(test)
library(ROCR)
ROCpred = prediction(predictTest,test$over50k)
as.numeric(performance(ROCpred,"auc")@y.values)
library(rpart)
library(rpart.plot)
treeModel = rpart(over50k ~ .,data=train, method = "class")
predictTree = predict(treeModel,newdata = test, type = "class")
table(test$over50k,predictTree)
(9243+1596)/nrow(test)
predictROC = predict(treeModel,newdata = test)
pred = prediction(predictROC[,2],test$over50k)
perf = performance(pred, "tpr","fpr")
AUC =  as.numeric(performance(pred, "auc")@y.values)
set.seed(1)
trainSmall = train[sample(nrow(train), 2000), ]
set.seed(1)
library(randomForest)
forestModel = randomForest(over50k ~ . , data=trainSmall)
predictForest = predict(forestModel,newdata = test)
table(test$over50k,predictForest)
(9586+1093)/nrow(test)
vu = varUsed(forestModel, count=TRUE)
vusorted = sort(vu, decreasing = FALSE, index.return = TRUE)
dotchart(vusorted$x, names(forestModel$forest$xlevels[vusorted$ix]))
cartGrid = expand.grid( .cp = seq(0.002,0.1,0.002))
set.seed(2)
treeModel2 = rpart(over50k ~ .,data=train, method = "class", cp = cartGrid)
newTreePredict <- predict(treeModel2, newdata=test, type="class")
table(test$over50k, newTreePredict)
(9178+1838)/nrow(test)
prp(treeModel2)