library(tm)
tweets = read.csv("./data/tweets.csv",stringsAsFactors = FALSE)
corpus = Corpus(VectorSource(tweets$Tweet))
corpus = tm_map(corpus,content_transformer(tolower))
corpus = tm_map(corpus, PlainTextDocument)
corpus = tm_map(corpus, removePunctuation)
corpus = tm_map(corpus,removeWords,stopwords("english"))
dtm = DocumentTermMatrix(corpus)
AllTweets = as.data.frame(as.matrix(dtm))
ncol(AllTweets)
library(wordcloud)
wordcloud(colnames(AllTweets),colSums(AllTweets),scale=c(2, 0.5))
corpus2 = Corpus(VectorSource(tweets$Tweet))
corpus2 = tm_map(corpus2,content_transformer(tolower))
corpus2 = tm_map(corpus2, PlainTextDocument)
corpus2 = tm_map(corpus2, removePunctuation)
corpus2 = tm_map(corpus2,removeWords,c("apple",stopwords("english")))
dtm2 = DocumentTermMatrix(corpus2)
AllTweets2 = as.data.frame(as.matrix(dtm2))
wordcloud(colnames(AllTweets2),colSums(AllTweets2),scale=c(2, 0.5))
library(RColorBrewer)
display.brewer.all()